[tools]

# Git related tools
github-cli = "latest"
gs = "0.22.0"

# Go related tools
go = "1.25.4"
golangci-lint = "1"

# Newer replacements for Unix tools
bat = "0.25"
delta = "0.18"
fd = "10"
fzf = "0.62"
ripgrep = "14"

# Editors
helix = "25"
neovim = "0.11.1"

# JSON / YAML tools
fx = "36" # json playground
gojq = "0.12"
gron = "0.7" # greppable json
yq = "4"

# Other
tmux-fastcopy = "0.14.1"

[alias]
gs = "ubi:abhinav/git-spice[exe=gs]"
tmux-fastcopy = "ubi:abhinav/tmux-fastcopy"
ente = "ubi:ente-io/ente[tag_regex=cli-v0]"

[settings]
experimental = true
